In [1]:
from data import build_dataprovider,DATAPROVIDER

In [2]:
import config as cfg

In [10]:
test = build_dataprovider(cfg.dataprovider,DATAPROVIDER).get_loaders()

In [4]:
from utils import Registry
import torch.nn as nn

In [5]:
TEST  = Registry("TEST")

In [11]:
@TEST.register_module
class A:
    def __init__(self):
        self.a = nn.Linear(10,10)

TypeError: register_module() takes 1 positional argument but 2 were given

In [4]:
from utils import build_from_cfg

In [3]:
build_from_cfg

<function utils.build_from_cfg.build_from_cfg(cfg, registry)>

In [4]:
Registry

utils.Registry.Registry

In [12]:
import torch

In [13]:
ada = torch.optim.Adam

In [15]:
ada(params)

NameError: name 'params' is not defined

In [16]:
import torchvision

In [17]:
data = torchvision.datasets.CIFAR100(root = "C:\Users\lenovo\Desktop\代码复现\基础卷积模块\my_code\data")

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (Temp/ipykernel_15260/3087439646.py, line 1)

In [12]:
from classification import Vit_config 

In [13]:
Vit_config.batch_size

(64,)

In [7]:
import config as cfg

In [1]:
from taming.models import vqgan


In [8]:
from omegaconf import OmegaConf

In [9]:
config = OmegaConf.load(vqgan_c)

NameError: name 'vqgan_c' is not defined

In [3]:
cfg = dict(
    type = "VQGAN",
    
    model_cfg = "./pretrained/vqgan/model.yaml",
    ckpt_path = "./pretrained/vqgan/last.ckpt",
)

In [6]:
cfg["type"]

'VQGAN'

In [12]:
from taming.models import vqgan
from omegaconf import OmegaConf

In [13]:
model_cfg = OmegaConf.load("./pretrained/vqgan/model.yaml")
model = vqgan.VQModel(**model_cfg.model.params)

Working with z of shape (1, 256, 16, 16) = 65536 dimensions.
loaded pretrained LPIPS loss from taming/modules/autoencoder/lpips\vgg.pth
VQLPIPSWithDiscriminator running with hinge loss.


In [15]:
model.decode

<bound method VQModel.decode of VQModel(
  (encoder): Encoder(
    (conv_in): Conv2d(3, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (down): ModuleList(
      (0): Module(
        (block): ModuleList(
          (0): ResnetBlock(
            (norm1): GroupNorm(32, 128, eps=1e-06, affine=True)
            (conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
            (norm2): GroupNorm(32, 128, eps=1e-06, affine=True)
            (dropout): Dropout(p=0.0, inplace=False)
            (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          )
          (1): ResnetBlock(
            (norm1): GroupNorm(32, 128, eps=1e-06, affine=True)
            (conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
            (norm2): GroupNorm(32, 128, eps=1e-06, affine=True)
            (dropout): Dropout(p=0.0, inplace=False)
            (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)

In [1]:
from model import build_vae

In [4]:
model = build_vae(cfg)

Working with z of shape (1, 256, 16, 16) = 65536 dimensions.
loaded pretrained LPIPS loss from taming/modules/autoencoder/lpips\vgg.pth
VQLPIPSWithDiscriminator running with hinge loss.
Restored from ./pretrained/vqgan/last.ckpt


In [5]:
vqgan = model.model

In [37]:
# 处理图片
import torch 
from PIL import Image

img = Image.open("./test_img/mani.jpeg")

In [38]:
from torchvision import transforms

img2tensor = transforms.ToTensor()
img_resize = transforms.Resize((128,128))

img = img_resize(img)
img = img2tensor(img)


In [39]:
from einops import rearrange


img = rearrange(img,'c h w -> () c h w')


In [40]:
img.shape

torch.Size([1, 3, 128, 128])

In [41]:



[a, b, indices] = vqgan.encode(img)


In [42]:
a.shape

torch.Size([1, 256, 8, 8])

In [43]:
indices[2].shape

torch.Size([64, 1])

In [13]:
_, _, [_, _, indices] = vqgan.encoder(img)

ValueError: not enough values to unpack (expected 3, got 1)

In [32]:
res = rearrange(indices[2], 'b n -> n b')

In [34]:
res.shape

torch.Size([1, 256])

In [14]:
res = vqgan.decoder(img)

RuntimeError: Given groups=1, weight of size [512, 256, 3, 3], expected input[1, 3, 256, 256] to have 256 channels, but got 3 channels instead

In [5]:
for name,weight in model.named_parameters():
    if name.startswith('encoder'):
        continue
    elif name.startswith("decoder"):
        continue
    elif name.startswith("loss"):
        continue
    else:
        print(name)


    


AttributeError: 'VQGAN' object has no attribute 'named_parameters'

In [ ]:
model.quantize
  

VectorQuantizer(
  (embedding): Embedding(16384, 256)
)

In [41]:
import torch

In [43]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [1]:
from tokenizer.ptbtokenizer import PTBTokenizer

ModuleNotFoundError: No module named 'tokenizer.ptbtokenizer'

In [3]:
import requests


In [5]:
res = requests.get("https://38.media.tumblr.com/9f6c25cc350f12aa74a7dc386a5c4985/tumblr_mevmyaKtDf1rgvhr8o1_500.gif")


ConnectionError: HTTPSConnectionPool(host='38.media.tumblr.com', port=443): Max retries exceeded with url: /9f6c25cc350f12aa74a7dc386a5c4985/tumblr_mevmyaKtDf1rgvhr8o1_500.gif (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C68CABEB50>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

In [1]:
import torch 
a = torch.rand(5,5)

In [8]:
import time 
d = 0.0 
start = time.time() 
b = torch.rand(1)
c = b.item() 
d+=c
end = time.time()

print(start-end)

0.0


In [4]:
a.topk(3,1,True)

torch.return_types.topk(
values=tensor([[0.9093, 0.7285, 0.4208],
        [0.7621, 0.7522, 0.6023],
        [0.7345, 0.6040, 0.2977],
        [0.9843, 0.8727, 0.8485],
        [0.8059, 0.5407, 0.2876]]),
indices=tensor([[0, 2, 4],
        [4, 3, 2],
        [3, 0, 1],
        [2, 3, 1],
        [0, 4, 2]]))

In [5]:
model = torch.nn.Linear(10,4)

In [7]:
lr = 1e-5
optimizer = torch.optim.Adam(model.parameters(), lr=lr)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, 100)



In [23]:
print(scheduler.get_last_lr())
scheduler.step()

[9.801468428384718e-06]


In [1]:
from model.builder import build_attention

In [2]:
import torch 

In [3]:
q = torch.rand(2,196,512)
k = torch.rand(2,196,512)
v = torch.rand(2,196,512)


cfg = dict(
    type = "CrossAttention",
    dim = 512,
    seq_len = 196,
)
cross = build_attention(cfg)

In [5]:
res = cross(q,k,v)

In [6]:
res.shape

torch.Size([2, 196, 512])

In [8]:
res.sqrt()

tensor([[[0.4116,    nan,    nan,  ..., 0.3317, 0.4965, 0.3505],
         [0.3540,    nan,    nan,  ..., 0.3941, 0.4842, 0.4140],
         [0.3757,    nan,    nan,  ...,    nan, 0.5165, 0.1929],
         ...,
         [0.3509,    nan,    nan,  ..., 0.3251, 0.5163, 0.4364],
         [0.3499,    nan,    nan,  ..., 0.3973, 0.4836, 0.4160],
         [0.3270,    nan,    nan,  ...,    nan, 0.5027, 0.3078]],

        [[   nan, 0.4908,    nan,  ..., 0.4217, 0.5364, 0.1176],
         [0.3645, 0.1763, 0.1179,  ..., 0.4382, 0.5609, 0.4149],
         [0.4367,    nan, 0.0526,  ...,    nan, 0.5643, 0.4992],
         ...,
         [0.3763,    nan,    nan,  ..., 0.1638, 0.5459, 0.3838],
         [0.4511, 0.2912, 0.2910,  ..., 0.5265, 0.5960, 0.3238],
         [0.4451,    nan,    nan,  ...,    nan, 0.5590, 0.5305]]],
       grad_fn=<SqrtBackward0>)

In [10]:
a = torch.tensor(4.0)

In [11]:
a.sqrt()

tensor(2.)

In [1]:
from model.backbone.MAE import MAE_decoder

In [2]:
import torch

In [3]:
k=v = torch.rand(2,196,768)

In [4]:
mae = MAE_decoder(k=k,v=v)

In [5]:
mae.pos_embed.shape

torch.Size([1, 196, 768])

In [6]:
q = torch.rand(2,196,768)

In [8]:
res = mae(q)

In [9]:
from model.lc_head.pixel_head import Pixel_head

In [10]:
p_head = Pixel_head(768,768,224)

In [13]:
res.shape

torch.Size([2, 196, 768])

In [14]:
p_head(res).shape

torch.Size([2, 3, 224, 224])

In [15]:
p_head(res)

tensor([[[[ 0.2599,  0.3558,  0.1995,  ..., -0.5909,  0.0376,  0.3277],
          [ 0.4690,  0.2059,  0.2102,  ..., -0.3159, -0.1929, -0.0433],
          [-0.1667,  0.1067, -0.0665,  ..., -0.2226,  0.0710,  0.3109],
          ...,
          [ 0.2949,  0.1739, -0.0334,  ...,  0.5717,  0.3187,  0.2691],
          [ 0.0960,  0.4362,  0.1004,  ...,  0.0790, -0.1188, -0.3742],
          [ 0.4186, -0.0479,  0.5588,  ...,  0.4951,  0.0865,  0.2243]],

         [[ 0.1417,  0.0673,  0.4280,  ..., -0.2012,  0.1294, -0.1809],
          [ 0.0231,  0.1395, -0.1211,  ...,  0.1973, -0.2559,  0.3697],
          [ 0.1006,  0.1353,  0.1059,  ..., -0.0777, -0.1725,  0.4236],
          ...,
          [ 0.3345,  0.5359,  0.1225,  ..., -0.0997, -0.2874,  0.1136],
          [ 0.6391, -0.3493, -0.0382,  ..., -0.1273, -0.0654,  0.0527],
          [-0.7719, -0.2040,  0.3894,  ..., -0.1903,  0.2184, -0.2682]],

         [[ 0.4271, -0.3409, -0.1280,  ...,  0.2845, -0.2383,  0.2109],
          [ 0.4130, -0.1916, -

In [1]:
from model import build_model


init model 


In [2]:
import torch 
import torch.nn as nn
q = torch.rand(2,196,768)
image = torch.rand(2,196,768)


In [3]:
model_cfg=dict(type="MAE_IMAGE_EDIT",
                backbone_cfg=dict(
                    type="MAE_decoder",
                    dim=768,
                    seq_len=196,
                    num_heads=8,
                    dim_head=64,
                    depth=12,
                    qk_scale=None,
                    act_layer=nn.GELU,
                    norm_layer=nn.LayerNorm,
                    attn_dropout_ratio=0.,
                    proj_dropout_ratio=0.,
                ),
                lc_head_cfg=dict(
                    type="Pixel_head",
                    in_channels=768, 
                    out_channels=768, 
                    image_size=224
                ))

In [4]:
mae = build_model(model_cfg)

In [9]:
mae.named_parameters

<bound method Module.named_parameters of MAE_IMAGE_EDIT(
  (backbone): MAE_decoder(
    (blocks): ModuleList(
      (0): Block(
        (cross_attn): CrossAttention(
          (to_q): Linear(in_features=768, out_features=512, bias=False)
          (to_k): Linear(in_features=768, out_features=512, bias=False)
          (to_v): Linear(in_features=768, out_features=512, bias=False)
          (proj): Linear(in_features=512, out_features=768, bias=False)
          (attn_dropout): Dropout(p=0.0, inplace=False)
          (proj_dropout): Dropout(p=0.0, inplace=False)
        )
        (mlp): MLP(
          (fc1): Linear(in_features=768, out_features=1536, bias=True)
          (fc2): Linear(in_features=1536, out_features=768, bias=True)
          (act_layer): GELU()
          (dropout): Dropout(p=0.0, inplace=False)
        )
        (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      )
      (1): Block(
   

In [9]:
md = nn.ModuleList([nn.Linear(4,8),nn.Linear(8,4)])

In [11]:
md[0]

Linear(in_features=4, out_features=8, bias=True)

In [10]:
im = torch.rand(2,3,224,224)

In [12]:
im.view(im.shape[0],196,-1).shape

torch.Size([2, 196, 768])

In [13]:
mse = nn.MSELoss()

In [25]:
a = torch.rand(2,3,224,224)
b = torch.rand(2,3,224,224)

In [26]:
mse(a,b)

tensor(0.1671)

In [27]:
a

tensor([[[[0.2678, 0.4000, 0.1401,  ..., 0.3453, 0.0455, 0.3096],
          [0.9667, 0.6586, 0.3742,  ..., 0.9158, 0.6024, 0.1027],
          [0.8486, 0.0671, 0.6702,  ..., 0.6572, 0.8364, 0.4337],
          ...,
          [0.8033, 0.9275, 0.3847,  ..., 0.3043, 0.6739, 0.8078],
          [0.5000, 0.0207, 0.2489,  ..., 0.7825, 0.3379, 0.4941],
          [0.1643, 0.9999, 0.5679,  ..., 0.7846, 0.5650, 0.8935]],

         [[0.7043, 0.6295, 0.0260,  ..., 0.3776, 0.4815, 0.4126],
          [0.7342, 0.3417, 0.9252,  ..., 0.0889, 0.4272, 0.8498],
          [0.3567, 0.5172, 0.8666,  ..., 0.1701, 0.9207, 0.8394],
          ...,
          [0.1614, 0.1146, 0.0534,  ..., 0.7604, 0.1937, 0.4445],
          [0.2485, 0.7689, 0.1751,  ..., 0.1821, 0.8973, 0.2669],
          [0.6947, 0.4183, 0.2611,  ..., 0.0911, 0.4250, 0.3630]],

         [[0.6282, 0.0286, 0.0740,  ..., 0.7694, 0.8751, 0.0351],
          [0.7900, 0.2806, 0.4491,  ..., 0.1052, 0.2940, 0.5005],
          [0.8697, 0.7015, 0.5905,  ..., 0

In [28]:
b

tensor([[[[0.3447, 0.9950, 0.5160,  ..., 0.5268, 0.6850, 0.5588],
          [0.1558, 0.7767, 0.4152,  ..., 0.0321, 0.9498, 0.8650],
          [0.0566, 0.6618, 0.4440,  ..., 0.2115, 0.1993, 0.6864],
          ...,
          [0.9683, 0.0236, 0.5671,  ..., 0.9624, 0.1750, 0.8488],
          [0.4281, 0.4295, 0.2635,  ..., 0.2556, 0.7054, 0.0522],
          [0.8575, 0.5695, 0.1058,  ..., 0.8985, 0.1051, 0.6906]],

         [[0.3653, 0.6295, 0.3612,  ..., 0.0331, 0.5243, 0.1075],
          [0.2518, 0.1232, 0.3994,  ..., 0.0306, 0.6459, 0.4210],
          [0.3370, 0.9343, 0.8471,  ..., 0.7017, 0.9028, 0.0566],
          ...,
          [0.1485, 0.0859, 0.9495,  ..., 0.6821, 0.5276, 0.4501],
          [0.3898, 0.5578, 0.9542,  ..., 0.9516, 0.3513, 0.5330],
          [0.1197, 0.6169, 0.6895,  ..., 0.5877, 0.1295, 0.5973]],

         [[0.4695, 0.4530, 0.1421,  ..., 0.5820, 0.1949, 0.8778],
          [0.0044, 0.1689, 0.6099,  ..., 0.6338, 0.4649, 0.5343],
          [0.5821, 0.8589, 0.2071,  ..., 0